export const CAMPUS_MAP_DATA = [
  {
    id: "ks-block",
    svg_id: "ks-block",
    name: "KS Block",
    category: "Academic",
    shape: "rect",
    coords: { x: 500, y: 535, w: 150, h: 70 },
    gps: { lat: 10.7558, lng: 78.6520 },
    departments: ["ECE", "EEE", "ICE", "Communication Lab"],
    labs: ["Communication Systems Lab", "VLSI Lab"],
    faculty: ["Dr. M. Santhi (HOD ECE)"],
    office_timing: "8:30 AM - 5:00 PM",
    current_events: ["IEEE Student Project Expo"],
    nearby_facilities: ["CUB ATM (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "Secretary K. Santhanam Block. Key academic quad block hosting Communication Systems Lab, VLSI Lab, and ECE/EEE chambers."
  },
  {
    id: "rv-block",
    svg_id: "rv-block",
    name: "RV Block",
    category: "Academic",
    shape: "rect",
    coords: { x: 675, y: 490, w: 185, h: 70 },
    gps: { lat: 10.7565, lng: 78.6521 },
    departments: ["CSE", "IT", "Mathematics", "Principal Office", "COE"],
    labs: ["Main Computing Center"],
    faculty: ["Dr. D. Valavan (Principal)"],
    office_timing: "8:30 AM - 5:30 PM",
    current_events: ["Campus Placement Drive 2026"],
    nearby_facilities: ["Ganesha Temple (15m)"],
    image: "/assets/campus-bg.jpg",
    description: "RV Block (CSE Department / Main Block). Houses administrative services, Principal chamber, COE exam cell, Placement Cell, and main CSE labs."
  },
  {
    id: "bd-block",
    svg_id: "bd-block",
    name: "BD Block",
    category: "Academic",
    shape: "rect",
    coords: { x: 675, y: 330, w: 185, h: 50 },
    gps: { lat: 10.7572, lng: 78.6520 },
    departments: ["AI&DS", "AI&ML", "CSBS", "Main Library"],
    labs: ["AI Deep Learning Lab", "Central Digital Library"],
    faculty: ["Dr. R. Sumathi (HOD AI&DS)"],
    office_timing: "8:00 AM - 6:30 PM",
    current_events: ["Smart India Hackathon Mentorship"],
    nearby_facilities: ["JS Block (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "BD Block. The computing innovation hub. Houses AI&DS research labs, CSBS wing, and Central Library."
  },
  {
    id: "js-block",
    svg_id: "js-block",
    name: "JS Block",
    category: "Academic",
    shape: "rect",
    coords: { x: 675, y: 390, w: 185, h: 50 },
    gps: { lat: 10.7568, lng: 78.6522 },
    departments: ["Civil Engineering", "Santhanam Auditorium"],
    labs: ["Structural Testing Lab"],
    faculty: ["Dr. G. Vimalan (HOD Civil)"],
    office_timing: "8:30 AM - 5:00 PM",
    current_events: ["Symphony Cultural Fest"],
    nearby_facilities: ["RV Block (30m)"],
    image: "/assets/campus-bg.jpg",
    description: "JS Block. Dedicated to Civil Engineering classrooms, structural design labs, and the 1200-capacity Santhanam Auditorium."
  },
  {
    id: "temple",
    svg_id: "temple",
    name: "Ganesha Temple",
    category: "Religious",
    shape: "rect",
    coords: { x: 705, y: 575, w: 125, h: 40 },
    gps: { lat: 10.7562, lng: 78.6522 },
    departments: ["Shrine"],
    labs: ["Temple Courtyard"],
    faculty: ["Campus Priest"],
    office_timing: "6:00 AM - 7:30 PM",
    current_events: ["Morning & Evening Prayers"],
    nearby_facilities: ["RV Block (15m)"],
    image: "/assets/campus-bg.jpg",
    description: "Ganesha Temple (Vinayagar Temple). Campus shrine near main walkway where students pray before exams."
  },
  {
    id: "atm",
    svg_id: "atm",
    name: "CUB ATM",
    category: "Services",
    shape: "rect",
    coords: { x: 535, y: 615, w: 80, h: 40 },
    gps: { lat: 10.7558, lng: 78.6522 },
    departments: ["Banking"],
    labs: ["ATM Kiosk"],
    faculty: ["CUB Branch Manager"],
    office_timing: "24/7 Service",
    current_events: ["Cash Withdrawal Kiosk"],
    nearby_facilities: ["KS Block (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "24/7 City Union Bank (CUB) ATM kiosk. Cash withdrawals and fee payment receipt printing."
  },
  {
    id: "me-block",
    svg_id: "me-block",
    name: "ME Block",
    category: "Academic",
    shape: "rect",
    coords: { x: 500, y: 275, w: 150, h: 45 },
    gps: { lat: 10.7574, lng: 78.6511 },
    departments: ["Mechanical Engineering"],
    labs: ["CAD/CAM Lab", "Thermal Lab"],
    faculty: ["HOD Mechanical"],
    office_timing: "8:30 AM - 5:00 PM",
    current_events: ["SAE Mini-Baja Fabrication"],
    nearby_facilities: ["Mechanical Workshop (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "ME Block. Mechanical wing housing theoretical draft rooms, CAD/CAM design labs, and thermal testing."
  },
  {
    id: "mech-workshop",
    svg_id: "mech-workshop",
    name: "Mechanical Workshop",
    category: "Academic",
    shape: "rect",
    coords: { x: 500, y: 225, w: 150, h: 40 },
    gps: { lat: 10.7578, lng: 78.6510 },
    departments: ["Mechanical Practice"],
    labs: ["Machine Shop", "Fitting Shop", "Welding Shop"],
    faculty: ["Workshop Superintendent"],
    office_timing: "8:30 AM - 4:30 PM",
    current_events: ["First Year Workshop Practice"],
    nearby_facilities: ["ME Block (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "Mechanical Central Workshop. Practice lab for carpentry, fitting, welding, and sheet metal works."
  },
  {
    id: "generator-room",
    svg_id: "generator-room",
    name: "Generator Room",
    category: "Utilities",
    shape: "rect",
    coords: { x: 500, y: 432, w: 150, h: 38 },
    gps: { lat: 10.7562, lng: 78.6513 },
    departments: ["Power Grid"],
    labs: ["Transformer Station"],
    faculty: ["Campus Engineer"],
    office_timing: "24/7 Power Desk",
    current_events: ["Routine Maintenance"],
    nearby_facilities: ["Mechanical Lab (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "Campus Power Substation. Generator backups ensuring uninterrupted lab power."
  },
  {
    id: "mech-lab",
    svg_id: "mech-lab",
    name: "Mechanical Lab",
    category: "Academic",
    shape: "rect",
    coords: { x: 500, y: 480, w: 150, h: 40 },
    gps: { lat: 10.7570, lng: 78.6512 },
    departments: ["Thermal / Fluid dynamics"],
    labs: ["Lathe Machining Lab"],
    faculty: ["Lab Superintendent"],
    office_timing: "8:30 AM - 4:30 PM",
    current_events: ["Fluid Mechanics Practicals"],
    nearby_facilities: ["KS Block (15m)"],
    image: "/assets/campus-bg.jpg",
    description: "Mechanical Lab complex. Thermal engineering test engines, fluid mechanics pumps, and lathe machining."
  },
  {
    id: "cafeteria",
    svg_id: "cafeteria",
    name: "Cafeteria",
    category: "Services",
    shape: "rect",
    coords: { x: 500, y: 330, w: 150, h: 50 },
    gps: { lat: 10.7566, lng: 78.6513 },
    departments: ["Dining & Refreshments"],
    labs: ["Food Court"],
    faculty: ["Canteen Manager"],
    office_timing: "7:30 AM - 6:00 PM",
    current_events: ["Fresh South Indian Breakfast & Lunch"],
    nearby_facilities: ["Stationery Shop (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "SCE Main Cafeteria. Freshly cooked vegetarian meals, snacks, juices, and coffee service."
  },
  {
    id: "stationery",
    svg_id: "stationery",
    name: "Stationery Shop",
    category: "Services",
    shape: "rect",
    coords: { x: 500, y: 390, w: 150, h: 32 },
    gps: { lat: 10.7564, lng: 78.6514 },
    departments: ["Academic Supplies"],
    labs: ["Xerox & Plotter Station"],
    faculty: ["Store Keeper"],
    office_timing: "8:00 AM - 6:00 PM",
    current_events: ["Record Notebook Distribution"],
    nearby_facilities: ["Generator Room (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "Campus Stationery shop. Note records, lab manuals, drawing sheets, printing, and photocopying."
  },
  {
    id: "basketball-court",
    svg_id: "basketball-court",
    name: "Basketball Court",
    category: "Sports",
    shape: "rect",
    coords: { x: 735, y: 705, w: 125, h: 70 },
    gps: { lat: 10.7552, lng: 78.6532 },
    departments: ["Outdoor Sports"],
    labs: ["Floodlit Acrylic Court"],
    faculty: ["Basketball Coach"],
    office_timing: "6:00 AM - 7:30 PM",
    current_events: ["Evening Basketball Session"],
    nearby_facilities: ["Volleyball Court (20m)"],
    image: "/assets/campus-bg.jpg",
    description: "Basketball Court. Fitted with LED floodlights and standard acrylic backboards."
  },
  {
    id: "volleyball-court",
    svg_id: "volleyball-court",
    name: "Volleyball Court",
    category: "Sports",
    shape: "rect",
    coords: { x: 500, y: 705, w: 215, h: 70 },
    gps: { lat: 10.7552, lng: 78.6530 },
    departments: ["Outdoor Sports"],
    labs: ["Sand Court"],
    faculty: ["Volleyball Coach"],
    office_timing: "6:00 AM - 6:30 PM",
    current_events: ["College League Match"],
    nearby_facilities: ["Basketball Court (20m)"],
    image: "/assets/campus-bg.jpg",
    description: "Volleyball Court. Sand pit court hosting college league and district sports selections."
  },
  {
    id: "football-ground",
    svg_id: "football-ground",
    name: "Football Ground",
    category: "Sports",
    shape: "rect",
    coords: { x: 525, y: 790, w: 240, h: 80 },
    gps: { lat: 10.7545, lng: 78.6533 },
    departments: ["Outdoor Sports"],
    labs: ["Natural Grass Field"],
    faculty: ["Football Coach"],
    office_timing: "6:00 AM - 6:30 PM",
    current_events: ["Annual Football Tournament"],
    nearby_facilities: ["Tennis Court (20m)"],
    image: "/assets/campus-bg.jpg",
    description: "Football Field. Natural grass court used for football practice and annual athletic meets."
  },
  {
    id: "tennis-court",
    svg_id: "tennis-court",
    name: "Tennis Court",
    category: "Sports",
    shape: "rect",
    coords: { x: 785, y: 780, w: 75, h: 90 },
    gps: { lat: 10.7545, lng: 78.6536 },
    departments: ["Outdoor Sports"],
    labs: ["Synthetic Hard Court"],
    faculty: ["Tennis Coach"],
    office_timing: "6:00 AM - 6:30 PM",
    current_events: ["Singles Tournament"],
    nearby_facilities: ["Football Ground (20m)"],
    image: "/assets/campus-bg.jpg",
    description: "Tennis Court. Synthetic hard court equipped for singles and doubles tournaments."
  },
  {
    id: "boys-hostel",
    svg_id: "boys-hostel",
    name: "Boys Hostel",
    category: "Hostel",
    shape: "rect",
    coords: { x: 580, y: 40, w: 270, h: 120 },
    gps: { lat: 10.7588, lng: 78.6522 },
    departments: ["Boys Residential Block"],
    labs: ["Study Hall", "Common Gym"],
    faculty: ["Chief Warden"],
    office_timing: "24/7 Residential",
    current_events: ["Hostel League Matches"],
    nearby_facilities: ["Main Cricket Ground (100m)"],
    image: "/assets/campus-bg.jpg",
    description: "Boys Hostel. Housing for male engineering students, equipped with Wi-Fi, study halls, and dining mess."
  },
  {
    id: "bus-boarding",
    svg_id: "bus-boarding",
    name: "Bus Boarding Point",
    category: "Transport",
    shape: "rect",
    coords: { x: 675, y: 235, w: 185, h: 80 },
    gps: { lat: 10.7548, lng: 78.6535 },
    departments: ["Transport Bay"],
    labs: ["Depot Bay"],
    faculty: ["Transport Officer"],
    office_timing: "7:00 AM - 6:30 PM",
    current_events: ["Evening Buses at 4:45 PM"],
    nearby_facilities: ["BD Block (15m)"],
    image: "/assets/campus-bg.jpg",
    description: "Main College Bus Bay. Boarding point for 25+ university buses connecting Trichy, Tanjore, and Pudukkottai."
  },
  {
    id: "security-room",
    svg_id: "security-room",
    name: "Security Room",
    category: "Services",
    shape: "rect",
    coords: { x: 500, y: 885, w: 95, h: 35 },
    gps: { lat: 10.7542, lng: 78.6538 },
    departments: ["Security"],
    labs: ["CCTV Control Room"],
    faculty: ["Chief Security Officer"],
    office_timing: "24/7 Security",
    current_events: ["Visitor Pass Logging"],
    nearby_facilities: ["Parking Lot (20m)"],
    image: "/assets/campus-bg.jpg",
    description: "Main Security Desk. Visitor entry logging, visitor passes, and CCTV monitoring."
  },
  {
    id: "parking-lot",
    svg_id: "parking-lot",
    name: "Parking Lot",
    category: "Transport",
    shape: "rect",
    coords: { x: 615, y: 885, w: 245, h: 40 },
    gps: { lat: 10.7540, lng: 78.6540 },
    departments: ["Parking Bay"],
    labs: ["EV Charging Docks"],
    faculty: ["Parking Supervisor"],
    office_timing: "7:30 AM - 7:00 PM",
    current_events: ["Vehicle Safety Patrol"],
    nearby_facilities: ["Security Room (20m)"],
    image: "/assets/campus-bg.jpg",
    description: "Covered student and staff parking lot for two-wheelers and cars."
  },
  {
    id: "tnsca-office",
    svg_id: "tnsca-office",
    name: "TNSCA Trichy Office",
    category: "Services",
    shape: "rect",
    coords: { x: 30, y: 235, w: 310, h: 100 },
    gps: { lat: 10.7565, lng: 78.6502 },
    departments: ["Sports Administration"],
    labs: ["Selection Bureau"],
    faculty: ["TNSCA Secretary"],
    office_timing: "9:00 AM - 5:00 PM",
    current_events: ["District Selection Trials"],
    nearby_facilities: ["Cricket Ground 2 (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "Trichy District Cricket Association admin headquarters. Manages local league matches and university cricket selections."
  },
  {
    id: "cricket-ground-2",
    svg_id: "cricket-ground-2",
    name: "Cricket Ground 2",
    category: "Sports",
    shape: "rect",
    coords: { x: 30, y: 355, w: 310, h: 285 },
    gps: { lat: 10.7560, lng: 78.6505 },
    departments: ["Outdoor Sports"],
    labs: ["Practice Field"],
    faculty: ["Assistant Physical Director"],
    office_timing: "6:00 AM - 6:30 PM",
    current_events: ["Junior Practice Nets"],
    nearby_facilities: ["TNSCA Office (10m)"],
    image: "/assets/campus-bg.jpg",
    description: "Cricket Practice Field 2. Used for junior training, nets practice, and physical education drills."
  },
  {
    id: "main-cricket",
    svg_id: "main-cricket",
    name: "Main Cricket Ground",
    category: "Sports",
    shape: "ellipse",
    coords: { cx: 240, cy: 100, rx: 200, ry: 65 },
    gps: { lat: 10.7578, lng: 78.6508 },
    departments: ["Physical Education"],
    labs: ["Sports Equipment Pavilion"],
    faculty: ["Physical Director"],
    office_timing: "6:00 AM - 7:00 PM",
    current_events: ["Inter-Collegiate League"],
    nearby_facilities: ["Boys Hostel (100m)"],
    image: "/assets/campus-bg.jpg",
    description: "Main Cricket Ground. International standard turf pitch hosting annual inter-collegiate tournaments."
  },
  {
    id: "cricket-ground-1",
    svg_id: "cricket-ground-1",
    name: "Cricket Ground 1",
    category: "Sports",
    shape: "rect",
    coords: { x: 30, y: 705, w: 310, h: 220 },
    gps: { lat: 10.7550, lng: 78.6500 },
    departments: ["Outdoor Sports"],
    labs: ["Practice Nets"],
    faculty: ["Physical Education"],
    office_timing: "6:00 AM - 6:30 PM",
    current_events: ["Nets Practice"],
    nearby_facilities: ["Toilet Block (inside)"],
    image: "/assets/campus-bg.jpg",
    description: "Cricket Practice Field 1. Large bottom-field for nets sessions and internal league matches."
  },
  {
    id: "toilet",
    svg_id: "toilet",
    name: "Toilet Block",
    category: "Utilities",
    shape: "rect",
    coords: { x: 50, y: 845, w: 80, h: 55 },
    gps: { lat: 10.7548, lng: 78.6498 },
    departments: ["Restrooms"],
    labs: ["Washrooms"],
    faculty: ["Maintenance Supervisor"],
    office_timing: "24/7 Service",
    current_events: ["Daily Cleaning"],
    nearby_facilities: ["Cricket Ground 1"],
    image: "/assets/campus-bg.jpg",
    description: "Sports field restrooms. Public washrooms for sports participants and ground visitors."
  }
];

export const LEGEND_CATEGORIES = [
  { key: "Academic", label: "Academic", icon: "school", color: "#1B4DA6" },
  { key: "Hostel", label: "Hostel", icon: "hotel", color: "#3F51B5" },
  { key: "Sports", label: "Sports", icon: "sports_cricket", color: "#2E7D32" },
  { key: "Transport", label: "Transport", icon: "directions_bus", color: "#607D8B" },
  { key: "Utilities", label: "Utilities", icon: "build", color: "#757575" },
  { key: "Services", label: "Services", icon: "storefront", color: "#E65100" },
  { key: "Religious", label: "Religious", icon: "temple_hindu", color: "#FFA000" }
];
