export const LOCALIZATION_DICTS = {
  en: {
    // Navigation
    home: "Home",
    dashboard: "Dashboard",
    clubs: "Clubs & Events",
    connect: "Connect",
    connectSubtitle: "Find hostel roommates compatible with your habits, or connect with senior mentors for academic and campus guidance.",
    campusInfo: "Campus Info",
    faculty: "Faculty Directory",
    map: "Campus Map",
    assistant: "Assistant",
    logout: "Log Out",
    exit: "Exit",
    back: "Back",
    continue: "Continue",

    // Welcome Page
    welcomeTitle: "Welcome to your campus journey.",
    welcomeSubtitle: "AI-powered companion guidance designed for incoming freshers. Organize your checklists, explore student clubs, and find roommates safely before your first day.",
    getStarted: "Get Started",
    alreadyAccount: "Already have an account? Log In",
    welcomeBack: "Welcome Back",
    loginSubtitle: "Log in to enter your freshman guide workspace.",
    username: "Username",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot Password?",
    login: "Log In",
    firstTime: "First time here?",
    createAccount: "Create Account",

    // Onboarding General
    personalInfo: "Personal Information",
    personalSubtitle: "Provide your name and administrative details to start.",
    fullName: "Full Name",
    rollNumber: "Register / Roll Number",
    emailAddress: "Email Address",
    preferredLanguage: "Preferred Language",
    stayType: "Stay Type",
    hosteller: "Hosteller",
    dayScholar: "Day Scholar",
    hostelBlock: "Hostel Residence Block",
    optional: "Optional",
    required: "Required",
    travelMode: "Mode of Travel",
    collegeBus: "College Bus",
    ownTransport: "Out Bus / Own Vehicle",

    // Onboarding Profile
    deptInterests: "Department & Interests",
    deptSubtitle: "Specify your core engineering stream and select chips.",
    enggDept: "Engineering Department",
    selectDept: "-- Select Department --",
    interestsQuestion: "What topics are you interested in?",
    describeGoals: "Describe your college goals in your own words",
    tellAboutSelf: "Tell us about yourself (e.g. 'I want to build mobile apps and join cultural art festivals...')",

    // Onboarding Credentials
    chooseCreds: "Choose Credentials",
    credsSubtitle: "Define your unique username and secure login password.",
    chooseUsername: "Choose Username",
    setPassword: "Set Password",
    confirmPassword: "Confirm Password",
    strength: "Strength",
    passwordsMatch: "Passwords do not match.",

    // Onboarding Summary
    confirmReg: "Confirm Registration",
    summarySubtitle: "Verify your freshman card details before deploying to Saranathan database.",
    fullNameLabel: "Full Name",
    streamDept: "Stream Department",
    stayTypeLabel: "Stay Type",
    registeredUsername: "Registered Username",
    areasOfInterest: "Areas of Interest",
    registerAccount: "Register Account",
    verifyProfile: "Verify Profile",

    // Onboarding Finished
    setupComplete: "Setup Complete!",
    setupCompleteSubtitle: "Your freshman profile is registered on the Saranathan database.",
    permanentUsername: "Permanent Username",
    enterPortal: "Enter PathMate Portal",
    detailsVerified: "Log in details verified. Press below to initialize your personalized PathMate freshers workspace.",

    // Dashboard
    weeklyDigest: "Freshers Weekly Digest",
    quickActions: "Quick Actions",
    checklistTitle: "Orientation Checklist",
    checklistDesc: "Complete academic and administrative tasks to settle in.",
    roommatesTitle: "Roommate Finder",
    roommatesDesc: "Connect with classmates matching your habits.",
    clubsTitle: "Clubs & Groups",
    clubsDesc: "Explore technology, arts, and cultural student bodies.",
    mentorsTitle: "Senior Connect",
    mentorsDesc: "Seek mentorship and placement advice from seniors.",
    snapshotTitle: "Campus Snapshot",
    newToSce: "New to SCE? Helpful Information",
    academicCalendar: "Academic Calendar 2026",
    inductionCeremony: "Induction Ceremony Assembly",
    canteenLocations: "Canteen & Dining Outlets",
    antiRaggingSafety: "Anti-Ragging Safety Regulations",
    emergencyCell: "Emergency Contact Numbers",
    welcomeTitleUser: "Welcome to Saranathan College,",
    companionReady: "Your freshers orientation companion is ready.",

    // Clubs Page
    aiPoweredMatches: "AI-Powered Matches",
    aiMatchesSubtitle: "Our Gemini model analyzed your custom goals and mapped these clubs for you:",
    whyThisMatches: "Why this matches you",
    viewRegSteps: "View Registration Steps",
    allSceClubs: "All SCE Clubs",
    allClubsSubtitle: "Browse the list of active student bodies at Saranathan.",
    optInClubText: "Opted In",
    joinClubText: "Opt In",

    // Connect Page
    roommateFinderTitle: "Safe Roommate Finder",
    roommateFinderSubtitle: "Contact information remains locked until BOTH students click 'Request to Connect'.",
    roommateMentorsTitle: "Senior Peer Mentors",
    roommateMentorsSubtitle: "Get guidance on examinations, placement cells, and Trichy transit hacks.",
    sharedInterests: "Shared Interests",
    mentorGuidesIn: "Guides freshers in",
    mentorTip: "Senior peer tip",
    sendMentorshipEmail: "Send Mentorship Email",
    requestToConnect: "Request to Connect",
    requestSent: "Request Sent",
    mutuallyConnected: "Mutually Connected! Contact:",

    // Campus Info / Faculty & Map
    facultyDirectoryTitle: "Department Faculty Directory",
    facultyDirectorySubtitle: "Lookup HOD and academic teaching professors at Saranathan.",
    searchFacultyPlaceholder: "Search by name, department, or designation...",
    campusLayoutTitle: "Campus Layout & Map Guide",
    campusLayoutSubtitle: "Click on any building label to query PathMate Assistant for directions.",
    queryAssistantForLoc: "Query Assistant for directions",

    // Chatbot Assistant
    groundedAssistantTitle: "PathMate Grounded Assistant",
    informationDesk: "Verified SCE Information Desk",
    assistantPlaceholder: "Ask about classrooms, warden office, library...",
    speakToAsk: "Speak to ask",
    clearHistoryBtn: "Clear Chat History",

    // Emergency Block
    emergencyHotlines: "Emergency Hotlines",
    safetyWelfarePanel: "Anti-Ragging Safety & Welfare Panel",
    immediateAssistance: "Immediate Assistance Hotlines",
    saranathanOffice: "Saranathan Main Office",
    academicDean: "Academic Dean Office",
    boysHostelWarden: "Boys Hostel Warden",
    girlsHostelWarden: "Girls Hostel Warden",
    localPoliceStation: "Local Police Station (K.K. Nagar)",
    antiRaggingHotline: "National Anti-Ragging Helpline",
    safetyDisclaimer: "Safety Safeguard: In case of physical harassment, hazing, or emotional bullying on campus, press the red dialer button immediately. Reporting can be made anonymously.",

    // Additional Audit Strings
    foundedHighlight: "Founded 1998",
    nbaHighlight: "NBA Accredited – 7 Depts",
    naacHighlight: "NAAC A+ Grade",
    annaHighlight: "Anna Univ Affiliated",
    aicteHighlight: "AICTE Approved",
    campusHighlight: "40-acre Campus",
    deptsHighlight: "9 Departments",
    busesHighlight: "25+ College Buses",
    checkingAvailability: "Checking availability...",
    cancelOnboardingConfirm: "Cancel onboarding process and return?",
    usernameRequired: "Username is required",
    usernameMinLen: "Username must be at least 4 characters",
    usernameMaxLen: "Username cannot exceed 20 characters",
    usernameFormatError: "Lowercase letters, numbers, underscores (_), and periods (.) only",
    usernameStartNumber: "Username cannot start with a number",
    usernameEndSpecial: "Username cannot end with a period or underscore",
    usernameConsecutiveSpecial: "Consecutive periods or underscores not allowed",
    usernameReserved: "This username is reserved",
    passwordRequired: "Password is required",
    passwordMinLen: "Password must be at least 8 characters long",
    passwordCriteria: "Must contain uppercase, lowercase, numbers, and a special character",
    usernameAvailable: "Username is available!",
    usernameTaken: "Username is already taken",
    exitBtn: "Exit",
    stepPersonal: "Personal",
    stepProfile: "Profile",
    stepCredentials: "Credentials",
    stepSummary: "Summary",
    stepWelcome: "Welcome",
    enterNamePlaceholder: "Enter your official full name",
    rollPlaceholder: "e.g. 26EC081",
    emailPlaceholder: "e.g. fresh@saranathan.ac.in",
    hostelBlockLabel: "Hostel Residence Block",
    hostelBBlockOption: "Boys Hostel",
    hostelGirlsBlockOption: "Girls Hostel",
    genderMale: "Male",
    genderFemale: "Female",
    interestOtherPlaceholder: "Specify other interests...",
    saranathanTitle: "Saranathan College of Engineering",
    freshersPortal: "Freshers Portal",
    authGate: "Authentication Gate",
    pleaseEnterBoth: "Please enter both username and password.",
    incorrectCreds: "Incorrect username or password.",
    passwordRecoveryAlert: "Please contact your department coordinator to request password recovery.",
    confirmLogout: "Are you sure you want to log out?",
    footerText: "Saranathan College of Engineering • Panjappur, Trichy",
    moreLabel: "More",
    roommateMatchTitle: "Safe Roommate Finder",
    dayScholarOptInTitle: "You are registered as a Day Scholar",
    dayScholarOptInDesc: "The roommate matchmaker is for hostel residents. Click below to opt-in if your accommodation has changed.",
    optInHostelBtn: "Opt-In as Hostel Resident",
    confirmOptInHostel: "Are you sure you want to opt-in as a hostel resident?",
    noRoommatesFound: "No roommates found",
    noRoommatesDesc: "No potential roommates match your exact filter selections.",
    filterAll: "All",
    filterSleepEarly: "Early Risers",
    filterSleepLate: "Night Owls",
    searchPlaceholderRoommates: "Search by name or origin town...",
    searchPlaceholderSeniors: "Search by name or advisor topic...",
    mentorLabel: "Senior Connect",
    selectDeptFilter: "Select Department",
    selectTopicFilter: "Select Advisor Topic",
    noSeniorsFound: "No senior advisors found",
    noSeniorsDesc: "Try broadening your filter criteria or search query.",
    studentDesk: "Student Desk",
    exploreConfidenceTitle: "Explore your college confidently",
    exploreConfidenceDesc: "Discover student clubs, navigate academic building directories, connect with senior coordinators, and ask PathMate anything.",
    hostelPrivacyTitle: "SCE Hostel Privacy Protocol:",
    hostelPrivacyDesc: "Your profile is visible only to other verified freshman hostel residents. Contact info is only shared after a mutual connection request.",
    peerMentoringTitle: "SCE Peer Mentoring Policy:",
    peerMentoringDesc: "These seniors are verified NSS coordinators or student council members who opted-in to receive academic queries. Maintain professionalism in all communications.",
    rmSearchPlaceholder: "Search by name or hometown...",
    srSearchPlaceholder: "Search senior by name or advisory skill...",
    rmNoResultsTitle: "No roommates match your criteria",
    rmNoResultsDesc: "Try widening your search filters.",
    srNoResultsTitle: "No seniors match your query",
    srNoResultsDesc: "Try adjusting search or selecting \"All Departments\".",
    filterSchedules: "All Schedules",
    filterSpecialities: "All Specialities",
    filterSpecialitiesLabel: "Advisory area",
    filterSleepLabel: "Sleep habit",
    escalateHeader: "Unable to answer? Let's escalate.",
    escalateDesc: "Since this query requires manual admin guidance, here is a drafted message to email the Student Welfare Office.",
    openEmailBtn: "Open Academic Email",
    copy: "Copy",
    copied: "Copied",
    chatbotError: "I'm having trouble reaching the campus directory service. Please try again or ask an administrative mentor.",
    confirmClearHistory: "Are you sure you want to clear chat history?",
    studyHub: "Study Hub",
    studyHubTitle: "Study Hub",
    studyHubSubtitle: "Everything a Saranathan student needs for studying, preparing for exams, buying resources, and staying connected — all in one place.",
    academicResources: "Academic Resources",
    prevQuestionPapers: "Previous Year Question Papers",
    prevPapersDesc: "Access department-wise previous year question papers and college-prepared question banks for Internal Assessments and Anna University examinations.",
    openQuestionPaperDrive: "Open Question Paper Drive",
    curriculumSyllabus: "Curriculum & Syllabus",
    viewCurriculum: "View Curriculum",
    viewSyllabus: "View Syllabus",
    campusResources: "Campus Resources",
    campusWifi: "Campus Wi-Fi",
    wifiDescription: "Connect to high-speed campus internet. View credentials or open the login portal.",
    wifiPortalBtn: "Open Wi-Fi Portal",
    wifiConnectionGuide: "Wi-Fi Connection Guide",
    officialInstagram: "Official Instagram",
    instagramDescription: "Stay updated with official announcements, events, achievements, placements, cultural activities, and campus news.",
    visitInstagram: "Visit Instagram",
    learningResources: "Learning Resources",
    programming: "Programming",
    electronics: "Electronics",
    mathematics: "Mathematics",
    aptitude: "Aptitude",
    placement: "Placement",
    gate: "GATE",
    recommendedChannels: "Recommended YouTube Channels",
    studentServices: "Student Services",
    saraSell: "SaraSell",
    saraSellDescription: "Buy and sell books, calculators, stationery, records, lab kits, and other student essentials within the Saranathan College community.",
    openSaraSell: "Open SaraSell"
  },
  ta: {
    // Navigation
    home: "முகப்பு",
    dashboard: "டேஷ்போர்டு",
    clubs: "மன்றங்கள் & நிகழ்வுகள்",
    connect: "இணைப்பு",
    connectSubtitle: "உங்களது பழக்க வழக்கங்களுக்குப் பொருத்தமான அறைத்தோழர்களைக் கண்டறியவும், அல்லது கல்வி வழிகாட்டல்களுக்கு மூத்த மாணவர்களுடன் இணையவும்.",
    campusInfo: "வளாகத் தகவல்",
    faculty: "பேராசிரியர் விபரங்கள்",
    map: "வளாக வரைபடம்",
    assistant: "உதவியாளர்",
    logout: "வெளியேறு",
    exit: "வெளியேறு",
    back: "பின்னால்",
    continue: "தொடரவும்",

    // Welcome Page
    welcomeTitle: "உங்கள் கல்லூரி பயணத்திற்கு வரவேற்கிறோம்.",
    welcomeSubtitle: "புதிய மாணவர்களுக்காக வடிவமைக்கப்பட்ட AI-இயங்கும் வழிகாட்டி. உங்கள் சரிபார்ப்புப் பட்டியல்களை ஒழுங்கமைக்கவும், மாணவர் மன்றங்களை ஆராயவும் மற்றும் உங்கள் முதல் நாளுக்கு முன்னதாகவே அறைத்தோழர்களைப் பாதுகாப்பாகக் கண்டறியவும்.",
    getStarted: "தொடங்குங்கள்",
    alreadyAccount: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக",
    welcomeBack: "மீண்டும் வருக",
    loginSubtitle: "உங்கள் வழிகாட்டி பணியிடத்தில் நுழைய உள்நுழைக.",
    username: "பயனர் பெயர்",
    password: "கடவுச்சொல்",
    rememberMe: "என்னை நினைவில் கொள்",
    forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    login: "உள்நுழைக",
    firstTime: "இங்கு முதல் முறையா?",
    createAccount: "கணக்கை உருவாக்கு",

    // Onboarding General
    personalInfo: "தனிப்பட்ட தகவல்",
    personalSubtitle: "தொடங்குவதற்கு உங்கள் பெயர் மற்றும் நிர்வாக விவரங்களை வழங்கவும்.",
    fullName: "முழு பெயர்",
    rollNumber: "பதிவு எண்",
    emailAddress: "மின்னஞ்சல் முகவரி",
    preferredLanguage: "விருப்பமான மொழி",
    stayType: "தங்கும் வகை",
    hosteller: "விடுதி மாணவர்",
    dayScholar: "வீட்டிலிருந்து வருபவர்",
    hostelBlock: "விடுதி குடியிருப்பு கட்டிடம்",
    optional: "விருப்பத்திற்குரியது",
    required: "தேவைப்படுகிறது",
    travelMode: "பயண வகை",
    collegeBus: "கல்லூரி பேருந்து",
    ownTransport: "சொந்த வாகனம் / பிற பேருந்து",

    // Onboarding Profile
    deptInterests: "துறை & ஆர்வங்கள்",
    deptSubtitle: "உங்கள் பொறியியல் துறையைத் தேர்ந்தெடுத்து ஆர்வங்களைத் தேர்ந்தெடுக்கவும்.",
    enggDept: "பொறியியல் துறை",
    selectDept: "-- துறையைத் தேர்ந்தெடுக்கவும் --",
    interestsQuestion: "உங்களுக்கு என்ன தலைப்புகளில் ஆர்வம் உள்ளது?",
    describeGoals: "உங்கள் கல்லூரி இலக்குகளை உங்கள் சொந்த வார்த்தைகளில் விவரிக்கவும்",
    tellAboutSelf: "உங்களைப் பற்றி கூறுங்கள் (எ.கா. 'நான் மொபைல் ஆப்ஸ்களை உருவாக்க விரும்புகிறேன் மற்றும் கலை விழாக்களில் சேர விரும்புகிறேன்...')",

    // Onboarding Credentials
    chooseCreds: "சான்றுகளைத் தேர்வுசெய்க",
    credsSubtitle: "உங்கள் தனிப்பட்ட பயனர் பெயர் மற்றும் பாதுகாப்பான கடவுச்சொல்லை வரையறுக்கவும்.",
    chooseUsername: "பயனர் பெயரைத் தேர்வுசெய்க",
    setPassword: "கடவுச்சொல்லை அமைக்கவும்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    strength: "வலிமை",
    passwordsMatch: "கடவுச்சொற்கள் பொருந்தவில்லை.",

    // Onboarding Summary
    confirmReg: "பதிவை உறுதிப்படுத்தவும்",
    summarySubtitle: "சாரநாதன் தரவுத்தளத்தில் சேமிப்பதற்கு முன் உங்கள் விவரங்களைச் சரிபார்க்கவும்.",
    fullNameLabel: "முழு பெயர்",
    streamDept: "பொறியியல் துறை",
    stayTypeLabel: "தங்கும் வகை",
    registeredUsername: "பதிவு செய்யப்பட்ட பயனர் பெயர்",
    areasOfInterest: "ஆர்வமுள்ள பகுதிகள்",
    registerAccount: "கணக்கை பதிவு செய்யவும்",
    verifyProfile: "விவரங்களைச் சரிபார்",

    // Onboarding Finished
    setupComplete: "அமைப்பு முடிந்தது!",
    setupCompleteSubtitle: "உங்கள் புதிய மாணவர் சுயவிவரம் சாரநாதன் தரவுத்தளத்தில் வெற்றிகரமாக பதிவு செய்யப்பட்டுள்ளது.",
    permanentUsername: "நிரந்தர பயனர் பெயர்",
    enterPortal: "நுழைவாயிலில் நுழையவும்",
    detailsVerified: "உள்நுழைவு விவரங்கள் சரிபார்க்கப்பட்டன. உங்கள் தனிப்பயனாக்கப்பட்ட பணியிடத்தைத் தொடங்க கீழே அழுத்தவும்.",

    // Dashboard
    weeklyDigest: "வாராந்திர தகவல் தொகுப்பு",
    quickActions: "விரைவுச் செயல்பாடுகள்",
    checklistTitle: "வழிகாட்டி சரிபார்ப்புப் பட்டியல்",
    checklistDesc: "கல்வி மற்றும் நிர்வாகப் பணிகளை எளிதாக முடிக்கவும்.",
    roommatesTitle: "அறைத்தோழர் தேடல்",
    roommatesDesc: "உங்கள் பழக்கவழக்கங்களுடன் பொருந்தும் வகுப்புத் தோழர்களுடன் இணையுங்கள்.",
    clubsTitle: "மாணவர் மன்றங்கள்",
    clubsDesc: "தொழில்நுட்பம், கலை மற்றும் கலாச்சார மன்றங்களை ஆராயுங்கள்.",
    mentorsTitle: "மூத்த மாணவர் இணைப்பு",
    mentorsDesc: "மூத்த மாணவர்களிடமிருந்து வழிகாட்டுதல் மற்றும் வேலைவாய்ப்பு ஆலோசனைகளைப் பெறுங்கள்.",
    snapshotTitle: "வளாகத்தின் ஒரு பார்வை",
    newToSce: "சாரநாதனுக்கு புதியவரா? பயனுள்ள தகவல்",
    academicCalendar: "கல்வி காலண்டர் 2026",
    inductionCeremony: "தொடக்க விழா கூட்டம்",
    canteenLocations: "உணவகங்கள் & சிற்றுண்டிச்சாலைகள்",
    antiRaggingSafety: "கேலிவதை எதிர்ப்பு பாதுகாப்பு விதிகள்",
    emergencyCell: "அவசர தொடர்பு எண்கள்",
    welcomeTitleUser: "சாரநாதன் கல்லூரிக்கு உங்களை வரவேற்கிறோம்,",
    companionReady: "உங்களின் புதிய மாணவர் வழிகாட்டி தயாராக உள்ளது.",

    // Clubs Page
    aiPoweredMatches: "AI-ஆல் பரிந்துரைக்கப்படும் பொருத்தங்கள்",
    aiMatchesSubtitle: "எங்கள் ஜெமினி மாதிரி உங்கள் இலக்குகளை பகுப்பாய்வு செய்து இந்த மன்றங்களை உங்களுக்குப் பரிந்துரைக்கிறது:",
    whyThisMatches: "இது உங்களுக்கு ஏன் பொருந்துகிறது",
    viewRegSteps: "பதிவு செய்வதற்கான படிகளைப் பார்க்கவும்",
    allSceClubs: "அனைத்து சாரநாதன் மன்றங்கள்",
    allClubsSubtitle: "சாரநாதனில் உள்ள செயலில் உள்ள மாணவர் அமைப்புகளின் பட்டியலை உலாவுக.",
    optInClubText: "தேர்ந்தெடுக்கப்பட்டது",
    joinClubText: "தேர்ந்தெடு",

    // Connect Page
    roommateFinderTitle: "பாதுகாப்பான அறைத்தோழர் தேடல்",
    roommateFinderSubtitle: "இரு மாணவர்களும் 'இணைக்கக் கோரு' என்பதை அழுத்தும் வரை தொடர்பு விவரங்கள் பூட்டப்பட்டிருக்கும்.",
    roommateMentorsTitle: "மூத்த மாணவர் வழிகாட்டிகள்",
    roommateMentorsSubtitle: "தேர்வுகள், வேலைவாய்ப்பு மற்றும் திருச்சியில் தங்கும் வழிகளைப் பற்றிய வழிகாட்டுதலைப் பெறுங்கள்.",
    sharedInterests: "பகிரப்பட்ட ஆர்வங்கள்",
    mentorGuidesIn: "வழிகாட்டும் பகுதிகள்",
    mentorTip: "மூத்த மாணவர்களின் ஆलोசனைகள்",
    sendMentorshipEmail: "மின்னஞ்சல் மூலம் தொடர்புகொள்",
    requestToConnect: "இணைக்கக் கோரு",
    requestSent: "கோரிக்கை அனுப்பப்பட்டது",
    mutuallyConnected: "இருதரப்பும் இணைக்கப்பட்டது! தொடர்பு எண்:",

    // Campus Info / Faculty & Map
    facultyDirectoryTitle: "துறை பேராசிரியர்கள் விபரம்",
    facultyDirectorySubtitle: "துறைத் தலைவர்கள் மற்றும் பேராசிரியர்களின் விபரங்களை இங்கே காணலாம்.",
    searchFacultyPlaceholder: "பெயர், துறை அல்லது பதவி மூலம் தேடவும்...",
    campusLayoutTitle: "வளாக அமைப்பு & வரைபட வழிகாட்டி",
    campusLayoutSubtitle: "திசைகளை அறிய வரைபடத்தில் உள்ள கட்டிட லேபிள்களை அழுத்தவும்.",
    queryAssistantForLoc: "உதவியாளரிடம் வழி கேட்கவும்",

    // Chatbot Assistant
    groundedAssistantTitle: "சாரநாதன் வழிகாட்டி உதவியாளர்",
    informationDesk: "சரிபார்க்கப்பட்ட தகவல் மையம்",
    assistantPlaceholder: "வகுப்பறைகள், விடுதி அலுவலகம், நூலகம் பற்றி கேளுங்கள்...",
    speakToAsk: "பேசி கேளுங்கள்",
    clearHistoryBtn: "அரட்டை வரலாற்றை அழி",

    // Emergency Block
    emergencyHotlines: "அவசர எண்கள்",
    safetyWelfarePanel: "கேலிவதை எதிர்ப்பு & நலக் குழு",
    immediateAssistance: "உடனடி உதவிக்கான எண்கள்",
    saranathanOffice: "சாரநாதன் முதன்மை அலுவலகம்",
    academicDean: "கல்वि டீன் அலுவலகம்",
    boysHostelWarden: "மாணவர் விடுதி காப்பாளர்",
    girlsHostelWarden: "மாணவியர் விடுதி காப்பாளர்",
    localPoliceStation: "உள்ளூர் காவல் நிலையம் (கே.கே. நகர்)",
    antiRaggingHotline: "தேசிய கேலிவதை எதிர்ப்பு உதவி எண்",
    safetyDisclaimer: "பாதுகாப்பு எச்சரிக்கை: வளாகத்தில் ஏதேனும் உடல் ரீதியான துன்புறுத்தல் அல்லது கேலிவதை நடந்தால், உடனடியாக சிவப்பு அவசர பொத்தானை அழுத்தவும். பெயர் குறிப்பிடாமல் புகார் அளிக்கலாம்.",

    // Additional Audit Strings
    foundedHighlight: "நிறுவப்பட்டது 1998",
    nbaHighlight: "NBA அங்கீகாரம் பெற்ற 7 துறைகள்",
    naacHighlight: "NAAC A+ தரம்",
    annaHighlight: "அண்ணா பல்கலைக்கழக இணைப்பு",
    aicteHighlight: "AICTE அங்கீகாரம் பெற்றது",
    campusHighlight: "40 ஏக்கர் வளாகம்",
    deptsHighlight: "9 துறைகள்",
    busesHighlight: "25+ கல்லூரி பேருந்துகள்",
    checkingAvailability: "கிடைக்கும்தன்மை சரிபார்க்கப்படுகிறது...",
    cancelOnboardingConfirm: "சேர்க்கை செயல்முறையை ரத்து செய்துவிட்டு திரும்ப வேண்டுமா?",
    usernameRequired: "பயனர் பெயர் தேவைப்படுகிறது",
    usernameMinLen: "பயனர் பெயர் குறைந்தபட்சம் 4 எழுத்துக்களைக் கொண்டிருக்க வேண்டும்",
    usernameMaxLen: "பயனர் பெயர் 20 எழுத்துக்களைத் தாண்டக்கூடாது",
    usernameFormatError: "சிறிய எழுத்துக்கள், எண்கள், அண்டர்ஸ்கோர்கள் (_), மற்றும் புள்ளிகள் (.) மட்டுமே அனுமதிக்கப்படும்",
    usernameStartNumber: "பயனர் பெயர் எண்ணுடன் தொடங்கக்கூடாது",
    usernameEndSpecial: "பயனர் பெயர் புள்ளி அல்லது அண்டர்ஸ்கோருடன் முடியக்கூடாது",
    usernameConsecutiveSpecial: "தொடர்ச்சியான புள்ளிகள் அல்லது அண்டர்ஸ்கோர்கள் அனுமதிக்கப்படாது",
    usernameReserved: "இந்த பயனர் பெயர் ஒதுக்கப்பட்டுள்ளது",
    passwordRequired: "கடவுச்சொல் தேவைப்படுகிறது",
    passwordMinLen: "கடவுச்சொல் குறைந்தபட்சம் 8 எழுத்துக்கள் கொண்டிருக்க வேண்டும்",
    passwordCriteria: "பெரிய எழுத்து, சிறிய எழுத்து, எண் மற்றும் ஒரு சிறப்பு குறியீட்டை கொண்டிருக்க வேண்டும்",
    usernameAvailable: "பயனர் பெயர் கிடைக்கிறது!",
    usernameTaken: "பயனர் பெயர் ஏற்கனவே எடுக்கப்பட்டது",
    exitBtn: "வெளியேறு",
    stepPersonal: "தனிப்பட்ட",
    stepProfile: "சுயவிவரம்",
    stepCredentials: "சான்றுகள்",
    stepSummary: "சுருக்கம்",
    stepWelcome: "வரவேற்பு",
    enterNamePlaceholder: "உங்கள் அதிகாரப்பூர்வ முழுப் பெயரை உள்ளிடவும்",
    rollPlaceholder: "எ.கா. 26EC081",
    emailPlaceholder: "எ.கா. fresh@saranathan.ac.in",
    hostelBlockLabel: "விடுதி குடியிருப்பு கட்டிடம்",
    hostelBBlockOption: "மாணவர் விடுதி",
    hostelABlockOption: "மாணவர் விடுதி",
    hostelGirlsBlockOption: "மாணவியர் விடுதி",
    genderMale: "ஆண்",
    genderFemale: "பெண்",
    interestOtherPlaceholder: "மற்ற ஆர்வங்களை குறிப்பிடவும்...",
    saranathanTitle: "சாரநாதன் பொறியியல் கல்லூரி",
    freshersPortal: "புதிய மாணவர்கள் வலைவாசல்",
    authGate: "உள்நுழைவு வாயில்",
    pleaseEnterBoth: "பயனர் பெயர் மற்றும் கடவுச்சொல் இரண்டையும் உள்ளிடவும்.",
    incorrectCreds: "தவறான பயனர் பெயர் அல்லது கடவுச்சொல்.",
    passwordRecoveryAlert: "கடவுச்சொல் மீட்பைக் கோர உங்கள் துறை ஒருங்கிணைப்பாளரைத் தொடர்பு கொள்ளவும்.",
    confirmLogout: "நிச்சயமாக வெளியேற வேண்டுमा?",
    footerText: "சாரநாதன் பொறியியல் கல்லூரி • பஞ்சப்பூர், திருச்சி",
    moreLabel: "மேலும்",
    roommateMatchTitle: "பாதுகாப்பான அறைத்தோழர் தேடல்",
    dayScholarOptInTitle: "நீங்கள் வீட்டிலிருந்து வருபவராக பதிவு செய்துள்ளீர்கள்",
    dayScholarOptInDesc: "அறைத்தோழர் தேடல் விடுதி மாணவர்களுக்கானது. உங்கள் தங்குமிடம் மாறியிருந்தால் விடுதியில் சேர கீழே அழுத்தவும்.",
    optInHostelBtn: "விடுதி மாணவராக மாறவும்",
    confirmOptInHostel: "நிச்சயமாக விடுதி மாணவராக மாற விரும்புகிறீர்களா?",
    noRoommatesFound: "அறைத்தோழர்கள் யாரும் காணப்படவில்லை",
    noRoommatesDesc: "உங்கள் வடிகட்டி தேர்வுகளுடன் பொருந்தும் அறைத்தோழர்கள் யாரும் இல்லை.",
    filterAll: "அனைத்தும்",
    filterSleepEarly: "சீக்கிரம் எழுபவர்கள்",
    filterSleepLate: "இரவு நேரத்தவர்கள்",
    searchPlaceholderRoommates: "பெயர் அல்லது சொந்த ஊர் மூலம் தேடவும்...",
    searchPlaceholderSeniors: "பெயர் அல்லது ஆலோசனை தலைப்பு மூலம் தேடவும்...",
    mentorLabel: "மூத்த மாணவர் இணைப்பு",
    selectDeptFilter: "துறையைத் தேர்ந்தெடுக்கவும்",
    selectTopicFilter: "ஆலோசனை தலைப்பைத் தேர்ந்தெடுக்கவும்",
    noSeniorsFound: "மூத்த வழிகாட்டிகள் யாரும் காணப்படவில்லை",
    noSeniorsDesc: "உங்கள் தேடல் அளவுகோலை விரிவுபடுத்தி முயற்சிக்கவும்.",
    studentDesk: "மாணவர் மேசை",
    exploreConfidenceTitle: "நம்பிக்கையுடன் உங்கள் கல்லூரியை ஆராயுங்கள்",
    exploreConfidenceDesc: "மாணவர் மன்றங்களைக் கண்டறியவும், கல்விக்கூட கட்டிடங்களைக் கண்டறியவும், மூத்த வழிகாட்டிகளுடன் இணையவும் மற்றும் பாத்மேட்டிடம் எதையும் கேட்கவும்.",
    hostelPrivacyTitle: "மாணவர் விடுதி தனியுரிமை நெறிமுறை:",
    hostelPrivacyDesc: "உங்கள் சுயவிவரம் மற்ற விடுதி மாணவர்களுக்கு மட்டுமே தெரியும். இருபுறமும் விருப்பம் தெரிவித்த பின்னரே தொடர்பு எண் பகிரப்படும்.",
    peerMentoringTitle: "மூத்த மாணவர் வழிகாட்டுதல் கொள்கை:",
    peerMentoringDesc: "இந்த மாணவர்கள் கல்வி மற்றும் வளாக வழிகாட்டல்களை வழங்க விருப்பம் தெரிவித்தவர்கள். உங்களுடைய உரையாடல்கள் நாகரீகமான முறையில் அமையட்டும்.",
    rmSearchPlaceholder: "பெயர் அல்லது சொந்த ஊர் மூலம் தேடவும்...",
    srSearchPlaceholder: "பெயர் அல்லது ஆலோசனை தலைப்பு மூலம் தேடவும்...",
    rmNoResultsTitle: "பொருத்தமான அறைத்தோழர்கள் யாரும் காணப்படவில்லை",
    rmNoResultsDesc: "உங்கள் வடிகட்டிகளை மாற்றி முயற்சிக்கவும்.",
    srNoResultsTitle: "மூத்த வழிகாட்டிகள் யாரும் காணப்படவில்லை",
    srNoResultsDesc: "வடிகட்டிகளை மாற்றி அல்லது 'அனைத்து துறைகளும்' என்பதைத் தேர்ந்தெடுத்து முயற்சிக்கவும்.",
    filterSchedules: "அனைத்து அட்டவணைகளும்",
    filterSpecialities: "அனைத்து சிறப்புகளும்",
    filterSpecialitiesLabel: "ஆலோசனைப் பகுதி",
    filterSleepLabel: "உறங்கும் பழக்கம்",
    escalateHeader: "பதில் கிடைக்கவில்லையா? மேல்முறையீடு செய்வோம்.",
    escalateDesc: "இந்தக் கேள்விக்கு நிர்வாகியின் நேரடி வழிகாட்டுதல் தேவை என்பதால், மாணவர் நல அலுவலகத்திற்கு அனுப்ப மின்னஞ்சல் வரைவு இங்கே உள்ளது.",
    openEmailBtn: "மின்னஞ்சலைத் திறக்கவும்",
    copy: "நகலெடுக்கவும்",
    copied: "நகலெடுக்கப்பட்டது",
    chatbotError: "வளாக வழிகாட்டி சேவையை அணுகுவதில் சிரமம் உள்ளது. தயவுசெய்து மீண்டும் முயற்சிக்கவும் அல்லது நிர்வாக வழிகாட்டியைக் கேட்கவும்.",
    confirmClearHistory: "உரையாடல் வரலாற்றை நிச்சயமாக அழிக்க வேண்டுமா?",
    studyHub: "கல்வி மையம்",
    studyHubTitle: "கல்வி மையம்",
    studyHubSubtitle: "சாரநாதன் மாணவர்கள் படிப்பதற்கும், தேர்விற்குத் தயாராவதற்கும், பொருட்களை வாங்குவதற்கும், மற்றும் இணைப்பில் இருப்பதற்கும் தேவையான அனைத்தும் ஒரே இடத்தில்.",
    academicResources: "கல்வி ஆதாரங்கள்",
    prevQuestionPapers: "முந்தைய ஆண்டு வினாத்தாள்கள்",
    prevPapersDesc: "துறை வாரியான முந்தைய ஆண்டு வினாத்தாள்கள் மற்றும் கல்லூரி தயாரித்த வினா வங்கிகளை அணுகவும்.",
    openQuestionPaperDrive: "வினாத்தாள் டிரைவை திறக்கவும்",
    curriculumSyllabus: "பாடத்திட்டம் & சிலபஸ்",
    viewCurriculum: "பாடத்திட்டத்தைக் காண்க",
    viewSyllabus: "சிலபஸைக் காண்க",
    campusResources: "வளாக ஆதாரங்கள்",
    campusWifi: "வளாக வைஃபை",
    wifiDescription: "அதிவேக வளாக இணையத்துடன் இணையுங்கள். நற்சான்றுகளைக் காண்க அல்லது உள்நுழைவு பக்கத்தைத் திறக்கவும்.",
    wifiPortalBtn: "வைஃபை பக்கத்தைத் திறக்கவும்",
    wifiConnectionGuide: "வைஃபை இணைப்பு வழிகாட்டி",
    officialInstagram: "அதிகாரப்பூர்வ இன்ஸ்டாகிராம்",
    instagramDescription: "அதிகாரப்பூர்வ அறிவிப்புகள், நிகழ்வுகள், சாதனைகள், வேலைவாய்ப்புகள் மற்றும் வளாக செய்திகளுடன் புதுப்பித்த நிலையில் இருங்கள்.",
    visitInstagram: "இன்ஸ்டாகிராம் பக்கத்திற்குச் செல்லவும்",
    learningResources: "கற்றல் ஆதாரங்கள்",
    programming: "நிரலாக்கம்",
    electronics: "மின்னணுவியல்",
    mathematics: "கணிதம்",
    aptitude: "திறனறிவு",
    placement: "வேலைவாய்ப்பு",
    gate: "கேட் தேர்வு",
    recommendedChannels: "பரிந்துரைக்கப்பட்ட யூடியூப் சேனல்கள்",
    studentServices: "மாணவர் சேவைகள்",
    saraSell: "சாராசெல் (SaraSell)",
    saraSellDescription: "சாரநாதன் கல்லூரி சமூகத்திற்குள் புத்தகங்கள், கால்குலேட்டர்கள் மற்றும் பிற மாணவர் அத்தியாவசிய பொருட்களை வாங்கி விற்கவும்.",
    openSaraSell: "சாராசெல்லை திறக்கவும்"
  },
  hi: {
    // Navigation
    home: "होम",
    dashboard: "डैशबोर्ड",
    clubs: "क्लब और कार्यक्रम",
    connect: "कनेक्ट",
    connectSubtitle: "अपनी आदतों के अनुकूल छात्रावास रूममेट खोजें, या शैक्षणिक मार्गदर्शन के लिए वरिष्ठ छात्रों से जुड़ें।",
    campusInfo: "कैंपस की जानकारी",
    faculty: "संकाय निर्देशिका",
    map: "कैंपस मानचित्र",
    assistant: "सहायक",
    logout: "लॉग आउट",
    exit: "बाहर निकलें",
    back: "पीछे",
    continue: "जारी रखें",

    // Welcome Page
    welcomeTitle: "आपकी कैंपस यात्रा में आपका स्वागत है।",
    welcomeSubtitle: "नए छात्रों के लिए डिज़ाइन किया गया एआई-संचालित साथी मार्गदर्शन। अपनी चेकलिस्ट व्यवस्थित करें, छात्र क्लबों का पता लगाएं और अपने पहले दिन से पहले सुरक्षित रूप से रूममेट्स खोजें।",
    getStarted: "शुरू करें",
    alreadyAccount: "पहले से ही एक खाता है? लॉग इन करें",
    welcomeBack: "वापसी पर स्वागत है",
    loginSubtitle: "अपने नए गाइड कार्यक्षेत्र में प्रवेश करने के लिए लॉग इन करें।",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    rememberMe: "मुझे याद रखें",
    forgotPassword: "पासवर्ड भूल गए?",
    login: "लॉग इन करें",
    firstTime: "यहाँ पहली बार आए हैं?",
    createAccount: "खाता बनाएं",

    // Onboarding General
    personalInfo: "व्यक्तिगत जानकारी",
    personalSubtitle: "शुरू करने के लिए अपना नाम और प्रशासनिक विवरण प्रदान करें।",
    fullName: "पूरा नाम",
    rollNumber: "पंजीकरण / अनुक्रमांक",
    emailAddress: "ईमेल पता",
    preferredLanguage: "पसंदीदा भाषा",
    stayType: "रहने का प्रकार",
    hosteller: "छात्रावास निवासी",
    dayScholar: "डे स्कॉलर (बाहर रहने वाले)",
    hostelBlock: "छात्रावास ब्लॉक",
    optional: "वैकल्पिक",
    required: "आवश्यक",
    travelMode: "यात्रा का साधन",
    collegeBus: "कॉलेज बस",
    ownTransport: "स्वयं का वाहन / अन्य बस",

    // Onboarding Profile
    deptInterests: "विभाग और रुचियां",
    deptSubtitle: "अपने इंजीनियरिंग विभाग और रुचियों का चयन करें।",
    enggDept: "इंजीनियरिंग विभाग",
    selectDept: "-- विभाग चुनें --",
    interestsQuestion: "आप किन विषयों में रुचि रखते हैं?",
    describeGoals: "अपने शब्दों में कॉलेज के लक्ष्यों का वर्णन करें",
    tellAboutSelf: "अपने बारे में बताएं (जैसे: 'मुझे मोबाइल ऐप बनाना और सांस्कृतिक उत्सवों में भाग लेना पसंद है...')",

    // Onboarding Credentials
    chooseCreds: "क्रेडेंशियल चुनें",
    credsSubtitle: "अपना विशिष्ट उपयोगकर्ता नाम और सुरक्षित लॉगिन पासवर्ड सेट करें।",
    chooseUsername: "उपयोगकर्ता नाम चुनें",
    setPassword: "पासवर्ड सेट करें",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    strength: "मजबूती",
    passwordsMatch: "पासवर्ड मेल नहीं खाते हैं।",

    // Onboarding Summary
    confirmReg: "पंजीकरण की पुष्टि करें",
    summarySubtitle: "सारनाथन डेटाबेस में सहेजने से पहले अपने विवरण सत्यापित करें।",
    fullNameLabel: "पूरा नाम",
    streamDept: "विभाग",
    stayTypeLabel: "रहने का प्रकार",
    registeredUsername: "पंजीकृत उपयोगकर्ता नाम",
    areasOfInterest: "रुचि के क्षेत्र",
    registerAccount: "खाता पंजीकृत करें",
    verifyProfile: "विवरण सत्यापित करें",

    // Onboarding Finished
    setupComplete: "सेटअप पूरा हुआ!",
    setupCompleteSubtitle: "आपकी प्रोफाइल सारनाथन डेटाबेस में सफलतापूर्वक पंजीकृत हो गई है।",
    permanentUsername: "स्थायी उपयोगकर्ता नाम",
    enterPortal: "पोर्टल में प्रवेश करें",
    detailsVerified: "लॉगिन विवरण सत्यापित किए गए। व्यक्तिगत कार्यक्षेत्र शुरू करने के लिए नीचे दबाएं।",

    // Dashboard
    weeklyDigest: "साप्ताहिक समाचार सार",
    quickActions: "त्वरित कार्रवाई",
    checklistTitle: "ओरिएंटेशन चेकलिस्ट",
    checklistDesc: "शैक्षणिक और प्रशासनिक कार्यों को आसानी से पूरा करें।",
    roommatesTitle: "Roommate Finder",
    roommatesDesc: "अपनी आदतों से मेल खाने वाले सहपाठियों से जुड़ें।",
    clubsTitle: "छात्र क्लब",
    clubsDesc: "तकनीकी, कला और सांस्कृतिक क्लबों का पता लगाएं।",
    mentorsTitle: "सीनियर कनेक्ट",
    mentorsDesc: "वरिष्ठ छात्रों से परीक्षाओं और प्लेसमेंट पर मार्गदर्शन प्राप्त करें।",
    snapshotTitle: "कैंपस की एक झलक",
    newToSce: "सारनाथन में नए हैं? उपयोगी जानकारी",
    academicCalendar: "शैक्षणिक कैलेंडर 2026",
    inductionCeremony: "दीक्षांत समारोह सभा",
    canteenLocations: "कैंटीन और भोजनालय",
    antiRaggingSafety: "रैगिंग विरोधी सुरक्षा नियम",
    emergencyCell: "आपातकालीन संपर्क नंबर",
    welcomeTitleUser: "सारनाथन कॉलेज में आपका स्वागत है,",
    companionReady: "आपका नया छात्र ओरिएंटेशन साथी तैयार है।",

    // Clubs Page
    aiPoweredMatches: "एआई-संचालित मिलान",
    aiMatchesSubtitle: "हमारे जेमिनी मॉडल ने आपके लक्ष्यों का विश्लेषण किया और इन क्लबों की सिफारिश की है:",
    whyThisMatches: "यह आपसे क्यों मेल खाता है",
    viewRegSteps: "पंजीकरण के चरण देखें",
    allSceClubs: "सभी सारनाथन क्लब",
    allClubsSubtitle: "सारनाथन में सक्रिय छात्र संगठनों की सूची देखें।",
    optInClubText: "शामिल हैं",
    joinClubText: "शामिल हों",

    // Connect Page
    roommateFinderTitle: "सुरक्षित रूममेट खोजक",
    roommateFinderSubtitle: "दोनों छात्रों द्वारा 'कनेक्ट का अनुरोध' करने तक संपर्क विवरण छिपे रहेंगे।",
    roommateMentorsTitle: "सीनियर मेंटर्स",
    roommateMentorsSubtitle: "परीक्षाओं, प्लेसमेंट और त्रिची में परिवहन पर मार्गदर्शन प्राप्त करें।",
    sharedInterests: "साझा रुचियां",
    mentorGuidesIn: "मार्गदर्शन के क्षेत्र",
    mentorTip: "वरिष्ठ छात्रों की सलाह",
    sendMentorshipEmail: "ईमेल भेजें",
    requestToConnect: "कनेक्ट का अनुरोध करें",
    requestSent: "अनुरोध भेजा गया",
    mutuallyConnected: "आपस में जुड़े! संपर्क नंबर:",

    // Campus Info / Faculty & Map
    facultyDirectoryTitle: "विभागवार संकाय सूची",
    facultyDirectorySubtitle: "सारनाथन में विभागाध्यक्षों और प्रोफेसरों की सूची खोजें।",
    searchFacultyPlaceholder: "नाम, विभाग या पद से खोजें...",
    campusLayoutTitle: "कैंपस संरचना और गाइड",
    campusLayoutSubtitle: "दिशा-निर्देश जानने के लिए कैंपस मैप पर किसी भी इमारत पर क्लिक करें।",
    queryAssistantForLoc: "सहायक से दिशा-निर्देश पूछें",

    // Chatbot Assistant
    groundedAssistantTitle: "सारनाथन मार्गदर्शक सहायक",
    informationDesk: "सत्यापित सूचना डेस्क",
    assistantPlaceholder: "कक्षाओं, छात्रावास कार्यालय, पुस्तकालय के बारे में पूछें...",
    speakToAsk: "बोलकर पूछें",
    clearHistoryBtn: "चैट इतिहास मिटाएं",

    // Emergency Block
    emergencyHotlines: "आपातकालीन नंबर",
    safetyWelfarePanel: "रैगिंग विरोधी और छात्र कल्याण पैनल",
    immediateAssistance: "तत्काल सहायता हेल्पलाइन",
    saranathanOffice: "सारनाथन मुख्य कार्यालय",
    academicDean: "शैक्षणिक डीन कार्यालय",
    boysHostelWarden: "छात्र छात्रावास अधीक्षक",
    girlsHostelWarden: "छात्रावास अधीक्षिका",
    localPoliceStation: "स्थानीय पुलिस थाना (के.के. नगर)",
    antiRaggingHotline: "राष्ट्रीय रैगिंग विरोधी हेल्पलाइन",
    safetyDisclaimer: "सुरक्षा चेतावनी: कैंपस में किसी भी प्रकार के शारीरिक उत्पीड़न या रैगिंग के मामले में, तुरंत लाल आपातकालीन बटन दबाएं। आप गुमनाम रूप से भी शिकायत कर सकते हैं।",

    // Additional Audit Strings
    foundedHighlight: "स्थापना 1998",
    nbaHighlight: "NBA मान्यता प्राप्त – 7 विभाग",
    naacHighlight: "NAAC A+ ग्रेड",
    annaHighlight: "अन्ना विश्वविद्यालय संबद्ध",
    aicteHighlight: "AICTE स्वीकृत",
    campusHighlight: "40 एकड़ का कैंपस",
    deptsHighlight: "9 विभाग",
    busesHighlight: "25+ कॉलेज बसें",
    checkingAvailability: "उपलब्धता की जांच की जा रही है...",
    cancelOnboardingConfirm: "ऑनबोर्डिंग प्रक्रिया रद्द करके वापस जाएं?",
    usernameRequired: "उपयोगकर्ता नाम आवश्यक है",
    usernameMinLen: "उपयोगकर्ता नाम कम से कम 4 वर्णों का होना चाहिए",
    usernameMaxLen: "उपयोगकर्ता नाम 20 वर्णों से अधिक नहीं हो सकता",
    usernameFormatError: "केवल छोटे अक्षर, संख्याएं, अंडरस्कोर (_) और बिंदु (.) की अनुमति है",
    usernameStartNumber: "उपयोगकर्ता नाम संख्या से शुरू नहीं हो सकता",
    usernameEndSpecial: "उपयोगकर्ता नाम बिंदु या अंडरस्कोर पर समाप्त नहीं हो सकता",
    usernameConsecutiveSpecial: "लगातार बिंदु या अंडरस्कोर की अनुमति नहीं है",
    usernameReserved: "यह उपयोगकर्ता नाम आरक्षित है",
    passwordRequired: "पासवर्ड आवश्यक है",
    passwordMinLen: "पासवर्ड कम से कम 8 वर्णों का होना चाहिए",
    passwordCriteria: "इसमें अपरकेस, लोअरकेस, संख्याएं और एक विशेष वर्ण होना चाहिए",
    usernameAvailable: "उपयोगकर्ता नाम उपलब्ध है!",
    usernameTaken: "उपयोगकर्ता नाम पहले से लिया जा चुका है",
    exitBtn: "बाहर निकलें",
    stepPersonal: "व्यक्तिगत",
    stepProfile: "प्रोफ़ाइल",
    stepCredentials: "क्रेडेंशियल",
    stepSummary: "सारांश",
    stepWelcome: "स्वागत है",
    enterNamePlaceholder: "अपना आधिकारिक पूरा नाम दर्ज करें",
    rollPlaceholder: "जैसे: 26EC081",
    emailPlaceholder: "जैसे: fresh@saranathan.ac.in",
    hostelBlockLabel: "छात्रावास ब्लॉक",
    hostelBBlockOption: "छात्र छात्रावास",
    hostelABlockOption: "छात्र छात्रावास",
    hostelGirlsBlockOption: "छात्रावास (छात्राएं)",
    genderMale: "पुरुष",
    genderFemale: "महिला",
    interestOtherPlaceholder: "अन्य रुचियों को निर्दिष्ट करें...",
    saranathanTitle: "सारनाथन इंजीनियरिंग कॉलेज",
    freshersPortal: "नए छात्रों का पोर्टल",
    authGate: "प्रवेश द्वार",
    pleaseEnterBoth: "कृपया उपयोगकर्ता नाम और पासवर्ड दोनों दर्ज करें।",
    incorrectCreds: "गलत उपयोगकर्ता नाम या पासवर्ड।",
    passwordRecoveryAlert: "पासवर्ड रिकवरी का अनुरोध करने के लिए कृपया अपने विभाग समन्वयक से संपर्क करें।",
    confirmLogout: "क्या आप निश्चित रूप से लॉग आउट करना चाहते हैं?",
    footerText: "सारनाथन इंजीनियरिंग कॉलेज • पंजप्पुर, त्रिची",
    moreLabel: "अधिक",
    roommateMatchTitle: "सुरक्षित रूममेट खोजक",
    dayScholarOptInTitle: "आप डे स्कॉलर के रूप में पंजीकृत हैं",
    dayScholarOptInDesc: "रूमेमट खोजक छात्रावास निवासियों के लिए है। यदि आपका निवास बदल गया है तो छात्रावास में शामिल होने के लिए नीचे क्लिक करें।",
    optInHostelBtn: "छात्रावास निवासी के रूप में शामिल हों",
    confirmOptInHostel: "क्या आप निश्चित रूप से छात्रावास निवासी के रूप में शामिल होना चाहते हैं?",
    noRoommatesFound: "कोई रूममेट नहीं मिला",
    noRoommatesDesc: "कोई भी संभावित रूममेट आपके फ़िल्टर चयनों से मेल नहीं खाता है।",
    filterAll: "सभी",
    filterSleepEarly: "जल्दी उठने वाले",
    filterSleepLate: "देर रात तक जागने वाले",
    searchPlaceholderRoommates: "नाम या शहर से खोजें...",
    searchPlaceholderSeniors: "नाम या विषय से खोजें...",
    mentorLabel: "सीनियर कनेक्ट",
    selectDeptFilter: "विभाग चुनें",
    selectTopicFilter: "सलाह विषय चुनें",
    noSeniorsFound: "कोई सीनियर सलाहकार नहीं मिला",
    noSeniorsDesc: "अपने खोज मानदंडों को विस्तृत करने का प्रयास करें।",
    studentDesk: "छात्र डेस्क",
    exploreConfidenceTitle: "आत्मविश्वास के साथ अपने कॉलेज की खोज करें",
    exploreConfidenceDesc: "छात्र क्लबों का पता लगाएं, शैक्षणिक भवनों की खोज करें, वरिष्ठ संरक्षकों से जुड़ें और पाथमेट से कुछ भी पूछें।",
    hostelPrivacyTitle: "एससीई छात्रावास गोपनीयता नियम:",
    hostelPrivacyDesc: "आपकी प्रोफ़ाइल केवल अन्य सत्यापित नए छात्रावास निवासियों को दिखाई देती है। आपसी संबंध अनुरोध के बाद ही संपर्क जानकारी साझा की जाती है।",
    peerMentoringTitle: "एससीई पीयर मेंटरिंग नीति:",
    peerMentoringDesc: "ये वरिष्ठ छात्र सत्यापित एनएसएस समन्वयक या छात्र परिषद के सदस्य हैं जिन्होंने मार्गदर्शन प्रदान करने की सहमति दी है। पेशेवर लहजा बनाए रखें।",
    rmSearchPlaceholder: "नाम या शहर से खोजें...",
    srSearchPlaceholder: "नाम या विषय से खोजें...",
    rmNoResultsTitle: "कोई रूममेट आपके मापदंडों से मेल नहीं खाता",
    rmNoResultsDesc: "अपने खोज फ़िल्टर बदलने का प्रयास करें।",
    srNoResultsTitle: "कोई सीनियर सलाहकार नहीं मिला",
    srNoResultsDesc: "खोज बदलने या 'सभी विभाग' चुनने का प्रयास करें।",
    filterSchedules: "सभी कार्यक्रम",
    filterSpecialities: "सभी विशेषताएं",
    filterSpecialitiesLabel: "सलाह क्षेत्र",
    filterSleepLabel: "सोने की आदत",
    escalateHeader: "उत्तर नहीं मिला? आइए इसे आगे बढ़ाएं।",
    escalateDesc: "चूंकि इस प्रश्न के लिए मैन्युअल प्रशासनिक मार्गदर्शन की आवश्यकता है, इसलिए छात्र कल्याण कार्यालय को ईमेल करने के लिए एक तैयार संदेश नीचे दिया गया है।",
    openEmailBtn: "ईमेल खोलें",
    copy: "कॉपी करें",
    copied: "कॉपी कर लिया",
    chatbotError: "कैंपस निर्देशिका सेवा तक पहुँचने में समस्या हो रही है। कृपया पुनः प्रयास करें या प्रशासनिक सलाहकार से पूछें।",
    confirmClearHistory: "क्या आप निश्चित रूप से चैट इतिहास को मिटाना चाहते हैं?",
    studyHub: "अध्ययन केंद्र",
    studyHubTitle: "अध्ययन केंद्र",
    studyHubSubtitle: "एक सारनाथन छात्र को अध्ययन, परीक्षा की तैयारी, संसाधन खरीदने और जुड़े रहने के लिए आवश्यक सब कुछ — सब एक ही स्थान पर।",
    academicResources: "शैक्षणिक संसाधन",
    prevQuestionPapers: "पिछले वर्ष के प्रश्न पत्र",
    prevPapersDesc: "आंतरिक मूल्यांकन और अन्ना विश्वविद्यालय परीक्षाओं के लिए विभाग-वार पिछले वर्ष के प्रश्न पत्र और प्रश्न बैंक प्राप्त करें।",
    openQuestionPaperDrive: "प्रश्न पत्र ड्राइव खोलें",
    curriculumSyllabus: "पाठ्यचर्या और पाठ्यक्रम",
    viewCurriculum: "पाठ्यचर्या देखें",
    viewSyllabus: "पाठ्यक्रम देखें",
    campusResources: "कैंपस संसाधन",
    campusWifi: "कैंपस वाई-फाई",
    wifiDescription: "हाई-स्पीड कैंपस इंटरनेट से कनेक्ट करें। लॉगिन पोर्टल खोलें या कनेक्शन निर्देश देखें।" ,
    wifiPortalBtn: "वाई-फाई पोर्टल खोलें",
    wifiConnectionGuide: "वाई-फाई कनेक्शन निर्देश",
    officialInstagram: "आधिकारिक इंस्टाग्राम",
    instagramDescription: "आधिकारिक घोषणाओं, कार्यक्रमों, उपलब्धियों, प्लेसमेंट और कैंपस समाचारों के साथ अपडेट रहें।",
    visitInstagram: "इंस्टाग्राम पर जाएं",
    learningResources: "कक्षा संसाधन",
    programming: "प्रोग्रामिंग",
    electronics: "इलेक्ट्रॉनिक्स",
    mathematics: "गणित",
    aptitude: "योग्यता",
    placement: "प्लेसमेंट",
    gate: "गेट परीक्षा",
    recommendedChannels: "अनुशंसित यूट्यूब चैनल",
    studentServices: "छात्र सेवाएं",
    saraSell: "सारासेल (SaraSell)",
    saraSellDescription: "सारनाथ कॉलेज समुदाय के भीतर किताबें, कैलकुलेटर, स्टेशनरी और अन्य छात्र आवश्यक वस्तुएं खरीदें और बेचें।",
    openSaraSell: "सारासेल खोलें"
  }
};
